train_file: 'data/nlvr2/train.json'
val_file: 'data/nlvr2/dev.json'             
test_file: 'data/nlvr2/test1.json' 

image_root: '/home/mila/b/benno.krojer/scratch/nlvr2/images' 

image_res: 384
batch_size: 16 

bert_config: 'configs/config_bert.json'

alpha: 0.4
distill: True
warm_up: True
eval_ema: False

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







